### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by sergiopvilar** [amio/node-submod#1]
Hello,

I've installed via npm and I'm getting this error when triyng to sync a subtitle:

```

$ submod Downton.Abbey.S06E01.1080p.WEB-DL.AAC2.0.H.264-EsQ.srt :+6
/usr/local/lib/node_modules/submod/lib/sync.js:3
const fs = require('fs')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/submod/lib/index.js:8:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by amio** [comment]
Sorry for missing this issue >. <

Are you using Node.js under version 4.0?
I'm considering use `var` insteadof `const` but for now maybe most people already have latest Node.js installed.

**Comment by sergiopvilar** [comment]
@amio I really don't remember which version I was using hahaha
But if you want I cant test it again.

**Comment by amio** [comment]
Just added a CircleCI config, it should do the works for us now :)
